title: Shawn Price
description: Shawn Price is a leader and engineering manager who supports the learning and growth of software teams.
url: https://shawnprice.com
author:
  name: Shawn Price
name: Shawn Price
permalink: /:title/
sass:
  style: compressed
exclude: [
  Makefile,
  README.md,
  s3_website.yml,
  .env,
  .env_,
  Gemfile,
  Gemfile.lock,
  node_modules,
  package.json,
  package-lock.json,
  ga-lambda.py,
  Rakefile,
  loggly-lambda.py,
  S3ToLoggly.js
]
include: [
  _redirects
]
plugins: [
  jekyll-paginate,
  jekyll-seo-tag,
  jekyll-sitemap
]
timezone: America/Vancouver
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
defaults:
  - scope:
      path: 'fonts/*'
    values:
      sitemap: false
