author:
  name: Shawn Price
permalink: /:title/
sass:
  style: compressed
exclude: [
  Makefile,
  README.md,
  s3_website.yml,
  .env,
  .env_,
  Gemfile,
  Gemfile.lock,
  node_modules,
  package.json,
  package-lock.json,
  ga-lambda.py,
  Rakefile,
  loggly-lambda.py,
  S3ToLoggly.js
]
include: [
  _redirects
]
plugins: [
  jekyll-crosspost-to-medium,
  jekyll-paginate,
  jekyll-seo-tag,
  jekyll-sitemap
]
url: https://shawnprice.com
description: Shawn Price is a leader and engineering manager who supports the learning and growth of software teams.
timezone: America/Vancouver
title: Shawn Price
name: Shawn Price
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: draft
  license: cc-40-by-nc-sa
  text: '<p><i>Originally published at <a href="{{ url }}?utm_source=medium.com&amp;utm_medium=referral">shawnprice.com</a></i></p>'
  backdate: true
