permalink: /:year/:month/:day/:title/
cdn: http://d2g3c0l1k63iq2.cloudfront.net
sass:
  style: compressed
exclude: [Makefile, README.md, s3_website.yml]
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
url: https://shawnprice.com
description: Shawn Price is a leader and engineering manager who grows efficient and effective software teams.
